### PR TITLE
Friends Page, User Object, Where The Quack Am I

### LINKED ISSUE #25: [3pts] Frontend: Where the Quack am I?
**Fill in the blanks**:
As a student, I would like to be able to share 'where in the DCT I choose to sit' with friends, so that we can efficiently find each other and eat together.

**Definition of Done - Check as you go!**
- [ ] Tasks have been implemented
- [ ] Documented
- [ ] Passing Tests for each task
- [ ] Pull Request made
- [ ] Code Reviewed

### LINKED ISSUE #132: Create friends frontend; share status of where friend is sitting (may require some backend)
**Fill in the blanks**:
As a student, I would like to be able to see where my FRIENDS are seated, so that I can quickly glance at my friends list and join them.

**Describe the solution you'd like:**
- [ ] Talk to @Foxworth22 if you have any questions

**Definition of Done - Check as you go!**
- [ ] Tasks have been implemented
- [ ] Documented
- [ ] Passing Tests for each task
- [ ] Pull Request made
- [ ] Code Reviewed

### PR DESCRIPTION
**Pull request by RafaelPiloto10**
This pull request is part 1 of 2 that will implement `Where the Quack Am I`. This pull request focuses on refactoring the "Profile Page". All submenus in "Profile" were duplicates of what was in "Settings". As a result, I removed these and made the profile page become a "Friends" Page. 

This pull request focuses on the selection of the station. This meant implementing the route to get to the selection UI as well as displaying the current station and whether or not the location is being shared with friends. 

A majority of the files changed are a result of deleting the previous unused views. A chunk of additions comes from the logic implementation of the `User()` class, which follows suit with the `Menu()` accessed in a static way. In order to keep track of friends, we need `UserData` so we can access friends in a non-static way. 

Screenshots:

Screen Shot 2021-11-11 at 10 33 35 AM

Screen Shot 2021-11-11 at 10 33 48 AM

Screen Shot 2021-11-11 at 10 34 03 AM

### After clicking in the red box

Screen Shot 2021-11-11 at 10 34 30 AM

Screen Shot 2021-11-11 at 10 34 50 AM

### CODE REVIEW

**Comment by brendacano** [comment]
Could you explain whats happening in this PR/ticket? Is it basically the friend clicks "Sitting in section 1" and now the user knows the friend is sitting in section 1?

**Comment by RafaelPiloto10** [comment]
> Could you explain whats happening in this PR/ticket? Is it basically the friend clicks "Sitting in section 1" and now the user knows the friend is sitting in section 1?

It is not complete yet. I just want to be mindful of how many files I am changing, hence the `fix in progress` tag

**Comment by brendacano** [comment]
> > Could you explain whats happening in this PR/ticket? Is it basically the friend clicks "Sitting in section 1" and now the user knows the friend is sitting in section 1?
> 
> It is not complete yet. I just want to be mindful of how many files I am changing, hence the `fix in progress` tag

Gotcha

**Comment by brendacano** [comment]
I only looked at your summary so far. I know you are going to do the UI to make it show specific sections, do you need all the maps? Because I can upload all the maps with isolated seat sections to the google drive so it highlights a section instead of showing the entire map

**Comment by RafaelPiloto10** [comment]
> I only looked at your summary so far. I know you are going to do the UI to make it show specific sections, do you need all the maps? Because I can upload all the maps with isolated seat sections to the google drive so it highlights a section instead of showing the entire map

Nah -- we can do this later as an enhancement. For now I think this is good enough to get the feature out so we can finish as much as we can before the semester is over

**Comment by brendacano** [comment]
> > I only looked at your summary so far. I know you are going to do the UI to make it show specific sections, do you need all the maps? Because I can upload all the maps with isolated seat sections to the google drive so it highlights a section instead of showing the entire map
> 
> Nah -- we can do this later as an enhancement. For now I think this is good enough to get the feature out so we can finish as much as we can before the semester is over

Yup agreed.

**Review by brendacano — APPROVED** [review]
I like it. I can't think of anything to improve or change of your code

**Review by oreorz — APPROVED** [review]

**Pull request merged**
