### PR TITLE
Quack Am I Part 2

### LINKED ISSUE #25: [3pts] Frontend: Where the Quack am I?
**Fill in the blanks**:
As a student, I would like to be able to share 'where in the DCT I choose to sit' with friends, so that we can efficiently find each other and eat together.

**Definition of Done - Check as you go!**
- [ ] Tasks have been implemented
- [ ] Documented
- [ ] Passing Tests for each task
- [ ] Pull Request made
- [ ] Code Reviewed

### LINKED ISSUE #132: Create friends frontend; share status of where friend is sitting (may require some backend)
**Fill in the blanks**:
As a student, I would like to be able to see where my FRIENDS are seated, so that I can quickly glance at my friends list and join them.

**Describe the solution you'd like:**
- [ ] Talk to @Foxworth22 if you have any questions

**Definition of Done - Check as you go!**
- [ ] Tasks have been implemented
- [ ] Documented
- [ ] Passing Tests for each task
- [ ] Pull Request made
- [ ] Code Reviewed

### PR DESCRIPTION
**Pull request by RafaelPiloto10**
Merge my parent first! #135 

Implements the friends list tile:

Screen Shot 2021-11-11 at 3 51 59 PM

### CODE REVIEW

**Comment by brendacano** [comment]
I love that El Chapo is one of our friends lol

**Comment by brendacano** [comment]
Did we want the friends to display in a particular order? Like if they were ordered by how recently they shared their location?

**Comment by RafaelPiloto10** [comment]
> Did we want the friends to display in a particular order? Like if they were ordered by how recently they shared their location?

Def can order it however we'd like. For now and given time constraints, just displaying them as is.

**Comment by brendacano** [comment]
> > Did we want the friends to display in a particular order? Like if they were ordered by how recently they shared their location?
> 
> Def can order it however we'd like. For now and given time constraints, just displaying them as is. 

Okay. That could be part of like final touches if we want tk change it later on.

**Review by brendacano — APPROVED** [review]
I think it looks fine

**Comment by Foxworth22** [comment]
@oreorz please review this as soon as possible

**Pull request merged**
