### PR TITLE
Login & Sign Up Screens

### LINKED ISSUE #106: [8pts] Frontend: Registration Page
**Fill in the blanks**:
As a student, I would like to register, so that I can quacking access Quack.

**Describe the solution you'd like:**
- [x] emory email field
- [x] password
- [x] confirm password
- [x] register button
- [x] login button

**Definition of Done - Check as you go!**
- [x] Tasks have been implemented
- [x] Documented
- [x] Passing Tests for each task
- [x] Pull Request made
- [ ] Code Reviewed

### LINKED ISSUE #115: [8pts] Frontend: Login Page
**Fill in the blanks**:
As a student, I would like to login, so that I can quacking access Quack.

**Describe the solution you'd like:**
- [x] emory email field
- [x] password
- [x] register button
- [x] login button

**Definition of Done - Check as you go!**
- [x] Tasks have been implemented
- [x] Documented
- [x] Passing Tests for each task
- [x] Pull Request made
- [ ] Code Reviewed

### PR DESCRIPTION
**Pull request by RafaelPiloto10**
This PR adds Login and Sign Up Screens with proper routing.

- Form Validation is bear bones and can be improved at a later time. Validation is missing since backend is not ready to support it. Currently stores cached email and password locally on the user's device `Documents` which is inaccessible by other apps. Stored in plain-text for now for simplicity.
- Forgot password is non-functional
- Refactored loading screen to handle and page route changes that need a loading screen transition
- Added Auth and TestAuth classes to handle authentication
  - Added `test.env` to flutter app which will contain test user information. For now, it can be anything. Replicate the format from `sample.env` to get a basic test user up and running. Once we have a test user in the DB, that will replace our `test.env`

### Screenshots

Screen Shot 2021-10-31 at 11 31 15 AM

Screen Shot 2021-10-31 at 11 31 30 AM

### CODE REVIEW

**Review by brendacano — COMMENTED** [review]
omg 99% of these files were tests lol. I guess you just need to fix the codecov stuff because it seems fine to me

**Review by Foxworth22 — CHANGES_REQUESTED** [review]
Looks like you have two failing checks. Please resolve those or at least give an explanation for them.

**Review by brendacano — APPROVED** [review]
There were so many files but I looked at all of them. I'm not very familiar with this language but I think it all seems logical from what I saw. I can't really think of anything to improve it so as long as it works I think it is good

**Review by Foxworth22 — APPROVED** [review]
^Same as Brenda

**Pull request merged**
