### PR TITLE
Implement Abstract Nav

### PR DESCRIPTION
**Pull request by RafaelPiloto10**
# Parent (merge first): #40 

## Description
This pull request implements a reusable NavBar that follows the template provided in the prototype.

## Screenshots:

Screen Shot 2021-09-30 at 9 19 52 PM
Screen Shot 2021-09-30 at 9 19 59 PM

### CODE REVIEW

**Review by DDVD233 — APPROVED** [review]
I probably need to check how the nav bar works. But all good.

**Comment by DDVD233** [comment]
@RafaelPiloto10 I have updated the nav bar implementation. Let me know if there's anything not clear.

**Comment by RafaelPiloto10** [comment]
@DDavid233, nice job! everything looks good

**Review by brendacano — APPROVED** [review]

**Comment by brendacano** [comment]
All the comments I had for this were the same I had for #56. Not sure if either of them were reliant on each other especially since they were within similar files

**Review by DDVD233 — APPROVED** [review]
All good! I think you can set the top bar text to whatever the page is using the same method, but that can probably be finished later.

**Pull request merged**
