### PR TITLE
Today's Menu Page & Refactor

### LINKED ISSUE #49: [2pts] Home Screen
**Fill in the blanks**:
As a student, I would like to see the current menu upon launch, so that I can access the most relevant info first.

**Describe the solution you'd like:**
- [x] Add a title to identify the page
- [x] Create visual for displaying all currently served food, categorized by meal station
- [x] Have a 'filters' button to add functionality to later
- [x] Have a 'Today's Menus' button to add functionality to later
- [x] Trigger Screen after Opening Screen displays for ~3 seconds
- [x] Contains Nav Bar to add functionality to later

**Definition of Done - Check as you go!**
- [x] Tasks have been implemented
- [x] Documented
- [x] Passing Tests for each task
- [x] Pull Request made
- [x] Code Reviewed

### LINKED ISSUE #50: [5pts] Today's Menus Screen
**Fill in the blanks**:
As a student, I would like to be able to view all menus served today, so that I can plan my mealtimes for the current day.

**Describe the solution you'd like:**
- [x] Add a title to identify the page
- [x] Create view for all menus for today, organized by mealtime first and location second
- [x] Have a 'filters' button to add functionality to later
- [x] Have a 'back' button to add functionality to later
- [x] Contains Nav Bar to add functionality to later

**Definition of Done - Check as you go!**
- [x] Tasks have been implemented
- [x] Documented
- [x] Passing Tests for each task
- [x] Pull Request made
- [x] Code Reviewed

### PR DESCRIPTION
**Pull request by RafaelPiloto10**
- Update home-page
Screen Shot 2021-10-06 at 9 55 58 PM

-  add today's menus page
Screen Shot 2021-10-06 at 8 58 15 PM

- refactor core
- update tests

### CODE REVIEW

**Comment by Foxworth22** [comment]
I don't that I feel qualified to review this.

**Comment by RafaelPiloto10** [comment]
> I don't that I feel qualified to review this. 

All good, no one is. No one stated Dart as a language they would be comfortable reviewing. The language is still very similar to Java and would appreciate any feedback or comments you have.

**Review by DDVD233 — APPROVED** [review]
Great work. There is nothing in particular needs to be changed.

By the way, I see you used getVariable() instead of allowing access to class members directly. What are the advantages of this approach?

**Review by brendacano — APPROVED** [review]
I like the changes you made. I didn't find anything off or wierd.

**Comment by RafaelPiloto10** [comment]
> Great work. There is nothing in particular needs to be changed.
> 
> By the way, I see you used getVariable() instead of allowing access to class members directly. What are the advantages of this approach?

Since we are going with a static approach, it is going to be hard to differentiate between assignment and reference. Using setters and getters is more readable and maintainable if we ever want to do some pre-processing

**Pull request merged**
