### PR TITLE
#70 create login password

### PR DESCRIPTION
**Pull request by brendacano**
This is from the login ticket from sprint 4. The testing has been giving me issues and if someone has any suggestions on how to fix it?

When I run the tests it says

`{'detail': 'There was an error parsing the body'}`

for where the ` client.post("/register/", login)` is and I have done many different ways to try to fix it as you can see from my commented out code in `server_test.py`

### CODE REVIEW

**Comment by RafaelPiloto10** [comment]
@brendacano ensure to use `git pull origin dev` to get the latest updates from dev. You will need to resolve these conflicts before your branch can be merged.

**Comment by RafaelPiloto10** [comment]
@brendacano Take a look at this in the [docs](https://fastapi.tiangolo.com/tutorial/testing/#extended-testing-file). Here, they pass data as headers in JSON instead of the entire class itself in the tests. I did this on my local machine and got tests to pass.

**Comment by RafaelPiloto10** [comment]
> @brendacano Take a look at this in the [docs](https://fastapi.tiangolo.com/tutorial/testing/#extended-testing-file). Here, they pass data as headers in JSON instead of the entire class itself in the tests. I did this on my local machine and got tests to pass.

One way to format your tests can be:
```python
class Prams():
    def __init__(self, username: str, email: str, password: str, expects_err: bool):
        self.username = username
        self.email = email
        self.password = password
        self.expects_err = expects_err
    def to_json(self):
        return {"username": self.username, "email": self.email, "password": self.password}

test_cases = [Params(......), Params(.....), Params(......)]
for test_case in test_cases:
    resp = client.post("/login", json=test_case.to_json())
    assert "err" in resp == test_case.expects_err
    .... more validation here
```

**Comment by brendacano** [comment]
> > @brendacano Take a look at this in the [docs](https://fastapi.tiangolo.com/tutorial/testing/#extended-testing-file). Here, they pass data as headers in JSON instead of the entire class itself in the tests. I did this on my local machine and got tests to pass.
> 
> One way to format your tests can be:
> 
> ```python
> class Prams():
>     def __init__(self, username: str, email: str, password: str, expects_err: bool):
>         self.username = username
>         self.email = email
>         self.password = password
>         self.expects_err = expects_err
>     def to_json(self):
>         return {"username": self.username, "email": self.email, "password": self.password}
> 
> test_cases = [Params(......), Params(.....), Params(......)]
> for test_case in test_cases:
>     resp = client.post("/login", json=test_case.to_json())
>     assert "err" in resp == test_case.expects_err
>     .... more validation here
> ```

Thanks Raf! I will incorporate the json

**Pull request closed without merging**
